[tool.ruff]
line-length = 88

[tool.ruuf.lint]
select = ["E", "F", "I", "T20"] # it depends which to use in the end. Also very common is "A", but "T20" is NOT sooo common.

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.mypy]
namespace_packages = true
ignore_missing_imports = true
check_untyped_defs = true
