[tool.ruff]
# Maximale Zeilenlänge
line-length = 88
# Ignoriere E501 (Line too long) nicht mehr, da wir die Zeilen umgebrochen haben.
# Wir ignorieren nur T201 (print statements), da print in dieser CLI-App für Logs verwendet wird.
ignore = ["T201"]

[tool.mypy]
# mypy konfigurieren, um die Prüfung zu starten
# Stellt sicher, dass das mypy-Kommando alle relevanten Python-Dateien abdeckt:
files = ["src/", "tests/"]

# Externe Bibliotheken ignorieren, die keine Typ-Annotationen haben
# Hier ignorieren wir sklearn, da es keine mypy-freundliche Bibliothek ist.
# Wir ignorieren joblib, da es ebenfalls mypy-Probleme verursachen kann.
[[tool.mypy.overrides]]
module = [
    "sklearn.*", 
    "joblib", 
    "pandas"
]
ignore_missing_imports = true
